### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by xizmark** [AmbitEnergyLabs/Sequelocity.NET#20]
I think its time that we can the already stable library of sequelocity to provide support for PostgreSQL. 
Creating this issue to track it. Taylor has begun working on this and had some ideas to discuss.

**Comment by wolfester** [comment]
The go-to way of accessing PostgreSQL from .NET is using [Npgsql](http://www.npgsql.org/).  This library provides a mostly complete implementation of ADO.NET.  I was able to plug Npgsql into Sequelocity with minimal effort (will need thorough testing, of course).  

If we're ok with adding a dependency, adding PostgreSQL support should be fairly trivial.  If we want to avoid that, some work will need to be done (though Npgsql is open sourced and we could cut code out of it).

**Comment by xizmark** [comment]
The question is, can we cherry pick the code that is needed for this? I checked the license and they permit copying the code over.

Introduction of another library by default maybe a bit unnecessary. Let's wait for a deeper discussion on this from other folks in the org.

**Comment by jackfarrington** [comment]
Why does the driver have to be included with Sequelocity? The SQLite and
MySql drivers are not included. It is up to the consumer to understand they
need to add those dependencies, and the DB provider factory is used to load
the appropriate driver. I would think loading of the PostgreSQL driver
should work the same way.

**Comment by wolfester** [comment]
I didn't realize that's how Sequelocity was doing things.  Let me see if I can get that to work.

**Comment by jackfarrington** [comment]
Yeah, check out the GetDatabaseCommandFor* methods.

For instance,

        public static DatabaseCommand GetDatabaseCommandForMySql(string
connectionStringOrName = null)
        {
            return GetDatabaseCommand(connectionStringOrName,
"MySql.Data.MySqlClient");
        }

The DB provider factory name is specified in the call to
GetDatabaseCommand(), and ultimately after a few nested method calls, we
find DbProviderFactory dbProviderFactory =
DbProviderFactories.GetFactory(dbProviderFactoryInvariantName);

As long as the PostgreSQL driver implements
System.Data.Common.DbProviderFactory (which it almost certainly would in a
.NET driver) it should work the same as any of the others.

**Comment by wolfester** [comment]
Cool, I started diving in and found as much.  I need to create/run some tests, but I should be making a pull request soon.

**Comment by jackfarrington** [comment]
And it does:

https://github.com/npgsql/npgsql/blob/develop/src/Npgsql/NpgsqlFactory.cs

So it should be as simple* as adding an extra For method:

        public static DatabaseCommand
GetDatabaseCommandForPostgreSql(string connectionStringOrName = null)
        {
            return GetDatabaseCommand(connectionStringOrName,
"<whatevergoeshere>");
        }



* plus an enormous set of new tests...

**Comment by wolfester** [comment]
Yep. It was that simple.  I'm creating equivalent to everything in the mysql test suite for postgres.
