### ISSUE TITLE
Nullable Parameters

### ISSUE THREAD

**Issue by xizmark** [AmbitEnergyLabs/Sequelocity.NET#8]
I have found myself in need of writing a sql-query that had variable declared and assigned as NULL. However, the library implicitly does NOT assign NULL when a null is actually passed. 

For example: 
```sql
DECLARE @MyNumber SMALLINT = @pMyNumber
```
becomes
```sql
DECLARE @MyNumber SMALLINT = @pMyNumber
```
while we need it to be
```sql
DECLARE @MyNumber SMALLINT = NULL
```

We can achieve this via the following snippet. ( Not completely refactored and polished yet )
```cs
private static DatabaseCommand AddNullableParameter( this DatabaseCommand command, string parameterName, object parameterValue, DbType dbType )
        {
            object paramValue = parameterValue;

            if ( paramValue != null
                && parameterValue is string
                && string.IsNullOrWhiteSpace( parameterValue.ToString() ) )
            {
                paramValue = null;
            }

            command = paramValue == null
                ? command.AddParameter( parameterName, DBNull.Value )
                : command.AddParameter( parameterName, parameterValue, dbType );

            return command;
        }
```

Here, the usage of ```string.IsNullOrWhiteSpace``` can be argued against ```string.IsNullOrEmpty```. 
When ```AddNullableParameter``` is called, the caller's explicit intention of handling 'nullables' can be interpreted into the fact that when a parameter is a string, unless a valid value is supplied, it could be a null. In this case, whitespaces assigned to a 'nullable' , would be a NULL. Most variables could possibly get serialized from empty/default/null values to an empty or white-space string. 

It can also be argued that in the context of ```NULLABLE``` Parameter in this library, when a white-spaced empty string should always be interpreted as a valid user input. Which would mean that the code should handle 'string' parameters' validation with ```string.IsNullOrEmpty```.

Do shoot your comments/idea.

**Comment by xizmark** [comment]
Question - not quite sure how this would affect or even be compatible with the other DB technologies this lib support like ORACLE, PostGreSQL etc. 

Any thoughts on this?

**Comment by randyburden** [comment]
As noted in the following [pull request comments](https://github.com/AmbitEnergyLabs/Sequelocity.NET/pull/9#discussion_r31816079) one of the unit tests needs to be moved to a different project in order to get the continuous integration build to pass for this pull request.

**Comment by randyburden** [comment]
I've merged the pull request and moved the unit tests to the correct project and labeled this the v0.5 release in the following commit: 4c970f75a6dd194cd9e1131a892b4e353648753d
